### ISSUE TITLE
charToJstring 方法可以用吗

### ISSUE THREAD

**Issue by baoyongzhang** [weizongwei5/AESJniEncrypt#12]
我看代码里调用 charToJstring 注释掉了，是有什么问题么？NewStringUTF 乱码会 crash

**Comment by weizongwei5** [comment]
你可以改一下  还继续用 charToJstring  然后提交一个 mergerequest给我，我来覆盖一下代码。

**Comment by baoyongzhang** [comment]
提pr了，我把注释去掉了，继续使用charToJstring

**Comment by weizongwei5** [comment]
先测试一下。

**Comment by weizongwei5** [comment]
🤪我在外面啊啊啊啊啊啊！

**Comment by weizongwei5** [comment]
已修改，issues即将关闭了。
