### ISSUE TITLE
如何动态添加秘钥

### ISSUE THREAD

**Issue by dxy1046** [weizongwei5/AESJniEncrypt#18]
这个方案看起来是固定秘钥的用法，如果我使用动态秘钥有没有好的解决方案呢

**Comment by weizongwei5** [comment]
你常识自己修改代码，通过jni方法传递jstring进来。

**Comment by dxy1046** [comment]
好的，谢谢解答

**Comment by weizongwei5** [comment]
看这里：[JNIEncrypt#95](https://github.com/weizongwei5/AESJniEncrypt/blob/master/aesjni/src/main/cpp/JNIEncrypt.c#L95)


------------

decode  encode方法都会有getkey ()   你改为通过jni从java传递进来就好了。  

不管既然你用动态key的话，就把所有AES相关方法名改掉让别人看不出 你是aes算法。

**Comment by dxy1046** [comment]
后来我一想如果使用动态秘钥的话，再使用jni方式有点得不偿失了，这样只能做到使用jni来加解密，秘钥还是没办法隐藏，这只是个人见解，对加解密及APP安全方面没有太多的了解

**Comment by weizongwei5** [comment]
对，但是你可以做的是算法保密。

**Comment by weizongwei5** [comment]
或者你网络传递key，可以通过 网络传一个被enocde(key),客户端需要先通过jni  decode(str) 得到key，然后再用jni进行加解密。

**Comment by dxy1046** [comment]
恩，这个确实是可以做到加密算法的反破译和非法调用难度增加，谢谢
