### ISSUE TITLE
key怎么做处理？

### ISSUE THREAD

**Issue by deliangliao** [weizongwei5/AESJniEncrypt#2]
请问下：
1.真实的key为：1234567890abcdef，怎么处理成：NMTIzNDU2Nzg5MGFiY2RlZg？
2.加密结果要怎么处理，不让它出现特殊字符，如加号（+） 和 等号（=），只由字母和数字组成？

thanks.

**Comment by weizongwei5** [comment]
1."N"+base64("1234567890abcdef")=NMTIzNDU2Nzg5MGFiY2RlZg  
2.此处所指的 加密是 key的 加密存到key里，还是说 AES这个算法的的加密？

**Comment by weizongwei5** [comment]
1."N"+base64("1234567890abcdef")=NMTIzNDU2Nzg5MGFiY2RlZg
2.此处所指的 加密是指AES加密的结果？  如果是的话，我没法回答你怎么去除特殊符号，不知道为什么特殊符号影响了你。
