### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by zhouclcode** [weizongwei5/AESJniEncrypt#3]
有没有可能改成最新的camke来编译呢

**Comment by weizongwei5** [comment]
您好：目前是支持 makefile 和 gradle 插件 编译，两种应该都能满足您。您的提议，我会加入到以后的计划中去。

**Comment by zhouclcode** [comment]
好的 , 期待您的cmake版本

**Comment by weizongwei5** [comment]
我是说：如果你有时间，希望您加入我们的组织来完成这个计划。

**Comment by weizongwei5** [comment]
到这个组织下[https://github.com/Scavenges](https://github.com/Scavenges).

**Comment by zhouclcode** [comment]
我能力还是有点不足 , 我目前也是只知道怎么配置cmake , 对于jni里面的一些代码移植还是有点懵

**Comment by weizongwei5** [comment]
你只需要修改配置文件，代码不用改。

**Comment by zhouclcode** [comment]
我尝试修改过成cmake配置 , 但是编译不通过  , 也许是某个配置没搞好 , 我可以再尝试一下

**Comment by weizongwei5** [comment]
你是在AndroidStudio里配置CMake？

**Comment by zhouclcode** [comment]
是啊 , 2.3的已经支持了cmake了

**Comment by weizongwei5** [comment]
恩 ，你慢慢尝试，我有时间来改一下。

**Comment by zhouclcode** [comment]
ok

**Comment by weizongwei5** [comment]
讨论到此结束吧 ，谢谢您 。

**Comment by weizongwei5** [comment]
已经升级为Cmake
[commit:8241f7f3dc72c299f5642ccfd581cb69da291222](https://github.com/weizongwei5/AESJniEncrypt/commit/8241f7f3dc72c299f5642ccfd581cb69da291222)

**Comment by zhouclcode** [comment]
辛苦了
