### ISSUE TITLE
从cmake换回ndkbuild编译不通过?

### ISSUE THREAD

**Issue by zeroleo12345** [weizongwei5/AESJniEncrypt#5]
cmake正常编译, 但换回方法1, ndkbuild
### Windows平台报错:
![image](https://user-images.githubusercontent.com/13072815/34339238-7924d77e-e9ac-11e7-8e6d-2d73a5a6c373.png)

### Linux平台报错:
![image](https://user-images.githubusercontent.com/13072815/34339259-c3d36ccc-e9ac-11e7-9ba9-864a91e1de92.png)

**Comment by weizongwei5** [comment]
我现在身边没有电脑，手机上简单看你的日志在clang ，  你ndk配置了obfuscator 了没？看下我的教程。

**Comment by zeroleo12345** [comment]
我已经是把obfuscator关了, ollvm的开关应该只是这些编译参数吧. 想先编译下无混淆的版本, 待会再编译混淆的对比. 结果就这样
![image](https://user-images.githubusercontent.com/13072815/34339412-b0714b84-e9ae-11e7-95f5-08baa1cf18ca.png)

**Comment by zeroleo12345** [comment]
用ndkbuild成功编译了. 改少了个开关
![image](https://user-images.githubusercontent.com/13072815/34339945-18d60dfc-e9b6-11e7-85a1-f74e4cbb3257.png)

**Comment by weizongwei5** [comment]
抱歉！抱歉！刚刚在开车，未能及时回复，刚刚到家开电脑。

你好了是吗？  如果好了，那我可否关闭这个  issues。

**Comment by zeroleo12345** [comment]
嗯， 可以了， 您太客气。
这ollvm好像不支持windows，试了3天。。。现在换成linux终于可以编译了，现在在试下混淆效果。
另外cmake增加编译参数cFlags -fvisibility=hidden好像不会生效， IDA打开so还能看到函数名

**Comment by weizongwei5** [comment]
-fvisibility=hidden  这个我测试过 并没有什么卵用 ，我记得我在mk文件里有说明这个没有卵用。

**Comment by weizongwei5** [comment]
忽然发现这个issues 是已经关闭的 。

**Comment by zeroleo12345** [comment]
-fvisibility=hidden在ndkbuild下有用的， 我刚试了， 应该没眼花

**Comment by weizongwei5** [comment]
NDKbuild有用？   你是用IDA吧，你换到objdump试试。

**Comment by weizongwei5** [comment]
你说的有用是隐藏函数？ 我想要的是隐藏字符表。
当然，破解so文件不止有反编译，还有别的动态调试等等，后期这个仓库会做一些延伸拓展。欢迎star。

**Comment by zeroleo12345** [comment]
已star了。目前只想防住一些小白， 大神的话就由他去吧。

**Comment by weizongwei5** [comment]
好的。

**Comment by zeroleo12345** [comment]
你想隐藏字符表， 估计ollvm混淆字符串也能适合这个需求吧

**Comment by weizongwei5** [comment]
我是前期做的时候偷懒用字符串写到代码里，等我有时间，你review我的代码保证你看不到字符串，其实有很多更合适的方案隐藏key。先说到这里，我先忙去了。

**Comment by weizongwei5** [comment]
新版key的安全存储方案，初阶版本。[commit:fbf46a49183e84d160ae99a7e0127d206696847b](https://github.com/weizongwei5/AESJniEncrypt/commit/fbf46a49183e84d160ae99a7e0127d206696847b)
