### ISSUE TITLE
如何修改 Key

### ISSUE THREAD

**Issue by LandChanning** [weizongwei5/AESJniEncrypt#7]
请问如何将 key 修改一下啊
`
char *getKey() {
    int n = 0;
    char s[23];//"NMTIzNDU2Nzg5MGFiY2RlZg";

    s[n++] = 'N';
    s[n++] = 'M';
    s[n++] = 'T';
    s[n++] = 'I';
    s[n++] = 'z';
    s[n++] = 'N';
    s[n++] = 'D';
    s[n++] = 'U';
    s[n++] = '2';
    s[n++] = 'N';
    s[n++] = 'z';
    s[n++] = 'g';
    s[n++] = '5';
    s[n++] = 'M';
    s[n++] = 'G';
    s[n++] = 'F';
    s[n++] = 'i';
    s[n++] = 'Y';
    s[n++] = '2';
    s[n++] = 'R';
    s[n++] = 'l';
    s[n++] = 'Z';
    s[n++] = 'g';
    char *encode_str = s + 1;
    return b64_decode(encode_str, strlen(encode_str));

    //初版hidekey的方案
}
`

我改动了 s 的值后，decode就是乱码了，我在项目中也没发现定义 base64 之前的 key 的地方。
不好意思 c 小白，肯请告知。

**Comment by weizongwei5** [comment]
这代码里的key 其实是 "N"+base64("1234567890abcdef")

**Comment by weizongwei5** [comment]
我这里只是做简单的算法，你可以把这个算法写的更加的复杂。

**Comment by LandChanning** [comment]
好的，我试下
多谢
