### ISSUE TITLE
如何生成新key 

### ISSUE THREAD

**Issue by yemamumu** [weizongwei5/AESJniEncrypt#9]
您的c代码里写死了处理后的key，那我如果想要用自己的key，那我如何获取到处理后的key

**Comment by weizongwei5** [comment]
[issues/7](https://github.com/weizongwei5/AESJniEncrypt/issues/7)

**Comment by weizongwei5** [comment]
您好 ，还有疑问吗？没有疑问我关了issues啊?

**Comment by yemamumu** [comment]
问题已解决，再次感谢

**Comment by weizongwei5** [comment]
不用谢，上次回复您时正在忙，没有解释太多直接丢了一个链接，望见谅。
